- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami_ids # to get the ami id from the inventory file, we can use the group name as a variable and it will return the value of the group name which is the ami id
    sg_id: sg-0cbd4d3b40fa4e1e2 # security group id
    zone_id: "Z04484812P5RP9I48MRRL" # route53 zone id
    domain_name: "shivaprasad.fun"
    # we can pass instances through command line using -e
    instance:
      - mongodb
      - redis
      - mysql
      - rabbitmq
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2: # to create ec2 instance using amazon.aws.ec2 module
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instance }}"
    register: ec2_output

  # - name: print ec2 output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}" # to print the output of the ec2 module stored in the variable ec2_output

  # - name: print public ipaddress
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #     loop: "{{ ec2_output.results }}"

  - name: create r53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" # to create a record with the name of the instance and the domain name, for example mongodb.shivaprasad.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

# We are creating one record with public ip address only for frontend server but we can create record for all the servers by using loop and we can use the same loop for creating ec2 instance and creating r53 record, we can use the item variable to access the name of the instance and the public ip address of the instance, for example we can use item.item to access the name of the instance and item.instances[0].public_ip_address to access the public ip address of the instance.

  - name: create r53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}" # to create a record with the name of the domain name, for example shivaprasad.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}" # to get the public ip address of the first instance created which is frontend server and assign it to the value of the record
      overwrite: true
    when: item.item == "frontend" # to create the record only for frontend server, we can use when condition to check if the name of the instance is frontend or not, if it is frontend then it will create the record otherwise it will skip the task
    loop: "{{ ec2_output.results }}"