- name: setup rabbitmq server
  hosts: rabbitmq
  become: true
  tasks:
  - name: copy rabbitmq repo
    ansible.builtin.copy: # copy module is used to copy files from local to remote
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rebbitmq.repo
  
  - name: install rabbitmq server
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name: start and enable services
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: create and provide permissions to roboshop user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present